### PR TITLE
Added implementation for digitalWrite method

### PR DESCRIPTION
**Pull request by kwisii**
When unit testing my code, I wanted to know if the digitalWrite methods were called correctly.
So at the end of the tests I checked if certain pins were set by reading with digitalRead.
In the end my tests failed because digitalWrite had no implementation

### CODE REVIEW

**Comment by kwisii** [comment]
I just read MR #61. Am I correct that for this implementation the modes (OUTPUT, INPUT, INPUT_PULLUP) must be handled for the specific pins? 
In this case, another implementation would be needed.
Or do we have another problem?

**Comment by bxparks** [comment]
In an actual Arduino board, there is no relationship between the value written by the `digitalWrite()` and the value returned by `digitalRead()`. So I cannot accept this PR which causes a link between the 2. I think I explained this in #61.

The alternative is to use the same technique of #61. Create a static variable to hold the bit field of pin values (e.g. `static uint32_t digitalWriteValues`), and have `digitalWrite()` update this bit field. Then create a new method, call it `uint8_t digitalWriteValue(uint8_t pin)` which returns the previously written bit for that pin.

I don't understand your question about OUTPUT, INPUT, and INPUT_PULLUP.

**Comment by kwisii** [comment]
Now I added a digitalWrite implementation with no relation between read and write mechanism.
About the OUTPUT, INPUT, INPUT_PULLUP stuff:
I was thinking about the behavior on hardware if you define a pin as INPUT by pinMode, for example, but use it as OUTPUT by setting HIGH or LOW.
The compiler will not fail, but I think you won't get the desired behavior between digitalWrite and digitalRead processes.
So I thought this is the reason for separating these two methods.
Following https://docs.arduino.cc/learn/microcontrollers/digital-pins there is a small section about this, but I think it is not easy to handle this.
I'm also not sure if it makes sense to implement this behavior.
In any case, this should be a separate merge request then...

**Comment by bxparks** [comment]
I'm not sure it's worth trying to emulate the behavior of `pinMode()`, though I haven't spent a lot of time thinking about it. EpoxyDuino was designed to implement just enough of the Arduino API to allow compilation of the user's program on a Linux box. That's enough to run unit tests like AUnit, or to allow development of software algorithms, but not enough as a simulation of actual hardware. Simulation is far outside the scope of this project in my mind.

The rest of your PR looks great. Thanks for the cleanup and consistency.

**Comment by bxparks** [comment]
Added documentation here:
https://github.com/bxparks/EpoxyDuino#MockDigitalReadDigitalWrite

**Pull request merged**
