### PR TITLE
Explicitly set O_NONBLOCK to stdin while running tests #2

### PR DESCRIPTION
**Pull request by mmrazik**
While using EpoxyDuino under WSL (Windows Subsystem For Linux) on Windows 10 (running Ubuntu 20.04) I was consistently running into https://github.com/bxparks/EpoxyDuino/issues/2.
Essentially whenever I was running tests from command line, I had to press buttons on keyboard otherwise the main loop was stuck on read. Every keypress meant one execution of the `loop` and feeding some input was the only way how to run the tests.
In my case explicitly setting `stdin` to `O_NONBLOCK` mode fixed the problem.

Before my fix (note the `k` in output; it was me pressing `k` to progress with the test; also notice the long duration of the test -- it was mostly waiting for my input):
```
mmrazik@LAPTOP:/mnt/c/github/project$ tests/SampleTest.out
kTestRunner started on 1 test(s).
kkkTest correct passed.
kTestRunner duration: 6.956 seconds.
TestRunner summary: 1 passed, 0 failed, 0 skipped, 0 timed out, out of 1 test(s).
```

After my fix:
```
mmrazik@LAPTOP:/mnt/c/github/project$ tests/SampleTest.out
TestRunner started on 1 test(s).
Test correct passed.
TestRunner duration: 0.006 seconds.
TestRunner summary: 1 passed, 0 failed, 0 skipped, 0 timed out, out of 1 test(s).
```

### CODE REVIEW

**Comment by bxparks** [comment]
Thanks for the PR! As far as I can tell, this PR does not seem to fix #2, but it didn't make things *worse*. If I do something like `SampleTest.out | less`, I now see nothing on the `less` command and it terminates with an error status code, but that's better than just blocking, so I guess it's slightly better? But I will accept PR because it fixes your problem on WSL.

I think the problem with piping to `less` in #2 is that both the EpoxyDuino program and `less` attempt to read from the stdin in raw mode at the same time (since `less` needs to respond to keyboard inputs), and they conflict with each other. I probably need to detect this condition and do something in `main.cpp`, but I don't have sufficient knowledge of Linux/POSIX/Unix programming to figure this out, and it just hasn't been a high enough priority for me to spend time on it.

**Comment by mmrazik** [comment]
@bxparks seems like you are able to reproduce #2 at least with a limited success. How/what are you using? 

I tried multiple things (different terminals, running on native ubuntu and not WSL, ...) but I can't reproduce. I would try to have a look but right now I am a bit stuck.

**Comment by bxparks** [comment]
The problem seems to happen if too much data is printed to the `SERIAL_PORT_MONITOR`. (I have a handful of tests in one of my other projects that has between 260 to 390 tests). I created a minimal reproducible example and checked it in at `examples/PipeFail`. You should be able to reproduce by typing:
```
$ cd examples/PipeFail
$ make
$ ./PipeFail.out | less  # <-- fails
$ ./PipeFail.out < /dev/null | less # <-- succeeds
``

**Comment by mmrazik** [comment]
Thanks! 
However, I have still no luck with reproducing this :( Both WSL on Win10 and Ubuntu 20.04 on bare metal works for me. 
What operating system do you use?

**Pull request merged**
